project:
  type: website
  resources:
    - "papers/*.pdf"
  render:
    - "!AGENTS.md"
    - "*.qmd"
    - "**/*.qmd"
  post-render: 
    - ./utils/purge_css.sh
    - ./utils/clean_sitemap.sh
    - ./utils/check_links.sh --pipeline

website:
  title: "Ven Popov"
  description: "Ven Popov is a senior scientist in computational modeling at the Department of Psychology, University of Zurich."
  site-url: https://venpopov.com
  favicon: images/favicon.ico
  image: images/venpopov.png
  google-analytics: "G-ZVYQ98TZ00"
  twitter-card: true
  open-graph: true
  search: false
  navbar:
    logo: images/popov-lab-logo-transparent.png
    pinned: true
    left:
      - href: index.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: CV/index.qmd
        text: CV
      - text: R Packages
        menu:
          - href: https://venpopov.github.io/bmm/index.html
            text: bmm (Bayesian Measurement Modeling
          - href: https://venpopov.github.io/chkptstanr/index.html
            text: chkptstanr (Checkpointing for Stan)
          # - href: https://venpopov.github.io/Vmisc/index.html
          #   text: Vmisc (Miscellaneous R Functions)
      - href: posts.qmd
        text: Blog
  draft-mode: unlinked

format:
  html:
    theme: 
      dark: [cosmo, utils/theme-dark.scss]
      light: cosmo
    css: utils/styles.css
    toc: true
    highlight-style: monokai
    canonical-url: true
    grid: 
      sidebar-width: 250px

execute: 
  freeze: auto
  cache: true
